server:
  port: 8085
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: TEST-SERVICE
          uri: http://localhost:8080
          predicates:
            - Path=/**